name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        TS=$(date +%y%m%d.%H%M%S)
        go build -o chpath -ldflags "-X main.Version=$TS"
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o chpath.mac -ldflags "-X main.Version=$TS"

    - name: Strip Linux Binary
      run: strip chpath

    - name: Show Version
      run: ./chpath -v

    - name: Create Release
      run: |
          ver=$(./chpath -v | tail -1)
          echo "Detected version $ver"
          tar czf chpath.lin64.tgz chpath
          mv chpath.mac chpath
          tar czf chpath.mac64.tgz chpath
          env GITHUB_TOKEN=${{ secrets.RELEASE_KEY }} hub release create \
              --message "ver. $ver ($(date +'%d.%m.%Y %H:%M'))" \
              --attach chpath.lin64.tgz --attach chpath.mac64.tgz \
              "$ver"