name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        TS=$(date +%y.%m.%d.%H%M%S)
        go build -ldflags "-X main.Version=$TS" chpath.go

    - name: Strip
      run: strip chpath

    - name: Show Version
      run: ./chpath -v

    - name: Create Release
      run: |
          ver=$(./chpath | tail -1)
          echo "Detected version $ver"
          tar czf chpath.lin64.tgz chpath
          env GITHUB_TOKEN=${{ secrets.RELEASE_KEY }} hub release create \
              --message "ver. $ver ($(date +'%d.%m.%Y %H:%M'))" \
              --attach chpath.lin64.tgz \
              "$ver"